services:
  fuseki:
    image: stain/jena-fuseki:latest
    container_name: extremexp_fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./fuseki_data:/fuseki
      - ./data:/staging
    environment:
      - ADMIN_PASSWORD=admin_password # CHANGE THIS to a secure password
      - TDB=2
      - FUSEKI_DATASET_1=matic_papers_kg
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/$/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  kg_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: extremexp_kg_service
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - RUN_MODE=service  # Run in service mode instead of one-shot
    depends_on:
      fuseki:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  fuseki_data:
