version: '3.8'

services:
  parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: extremexp_parser
    volumes:
      - ./data:/app/data  # Mount local data dir into container's /app/data
                          # This way, input is read from local, output is written to local
    depends_on:
      - fuseki # Optional: wait for fuseki if you plan to upload directly
    # The command is defined by ENTRYPOINT in Dockerfile,
    # or you could override it here:
    # command: python src/main.py

  fuseki:
    image: stain/jena-fuseki:latest # Using the community image
    container_name: extremexp_fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./fuseki_data:/fuseki        # stain/jena-fuseki uses /fuseki for its data
      - ./data:/staging              # Mount local ./data to /staging for uploads
    environment:
      - ADMIN_PASSWORD=admin_password # CHANGE THIS to a secure password
      - TDB=2                         # To enable TDB2, as per stain/jena-fuseki docs
      - FUSEKI_DATASET_1=matic_papers_kg # Attempt to create a dataset named 'matic_papers_kg'
                                      # The actual database files for this will be in /fuseki/databases/matic_papers_kg
    # For stain/jena-fuseki, the command is often implicit or minimal,
    # as configuration is primarily through environment variables.
    # We remove the explicit 'command:' line that was intended for the official apache image.

volumes:
  fuseki_data:
